# Generated by Django 3.0.7 on 2020-08-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown', models.DateField()),
                ('total_assets', models.IntegerField(null=True)),
                ('total_liabilities', models.IntegerField(null=True)),
                ('total_equity', models.IntegerField(null=True)),
                ('total_capitalization', models.IntegerField(null=True)),
                ('common_stock', models.IntegerField(null=True)),
                ('capital_lease', models.IntegerField(null=True)),
                ('net_tangible', models.IntegerField(null=True)),
                ('working_capital', models.IntegerField(null=True)),
                ('invested_capital', models.IntegerField(null=True)),
                ('tangible_book', models.IntegerField(null=True)),
                ('total_debt', models.IntegerField(null=True)),
                ('share_issued', models.IntegerField(null=True)),
                ('ordinary_shares', models.IntegerField(null=True)),
            ],
        ),
    ]
